dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
  - smartcontractkit/chainlink-brownie-contracts@0.5.1
reports:
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
